### PR TITLE
Experimental escape_xml functionality

### PR DESCRIPTION
**Pull request by anssip**
I had problems using this crate in my project because:

- with the serialization feature enabled, it would not compile
- without serialization it failed to compile as well, but I managed to fix that by removing `get_time` and `get_expiry_time` from the Node struct, and adding `get_times_mut` to it

This PR fixes the compilation issues when serialization is not enabled.

### CODE REVIEW

**Comment by ssrlive** [comment]
Hi @anssip , 
Now I have time to check this crate code.
How about to add me as a publisher on `crates.io` and I add you as a co-contributor of this repo?

**Comment by ssrlive** [comment]
This test suit not passed.

https://github.com/ssrlive/keepass-rs/blob/2ed78b4fa32b73159589826393d2dbbe842c281e/src/xml_db/parse/mod.rs#L989-L990

**Comment by anssip** [comment]
I will check that failing unit test. Once the test passes, you could publish this repository to crates.io and I will make my project depend on it. And you add me as a co-contributor of this repo. (Or we can do as you proposed as well. Just thought that it might make sense to have this repository as the one people use and discard my fork)

**Comment by ssrlive** [comment]
I have sent the invite.

**Comment by anssip** [comment]
Should we squash all commits into one which then has a proper comment? This to fix that lint error.

**Comment by ssrlive** [comment]
Yes. But I want to know what are these additional modifications intended to achieve?

**Comment by ssrlive** [comment]
After this PR, let's begin from new repo and cut off the relationship of the upstream.  https://github.com/ssrlive/keepass-ng

And please send a invite from crates.io to me.

**Comment by anssip** [comment]
For me it’s OK to squash and loose the history regarding the additional commits. I’ll give you access in crates.io

**Comment by anssip** [comment]
Can we merge this now?

**Comment by ssrlive** [comment]
Does the `escape_xml` function comply with the keepass data specification?

**Comment by anssip** [comment]
I think escape_xml is fine as it only strips out characters that would break the XML document. However, these characters can be already filtered out outside of this library (that's what i'm doing in my project now) and we can  drop that commit that adds the `escape_xml` function.

**Comment by ssrlive** [comment]
In your project, can all keepass files pass the test?

**Comment by anssip** [comment]
Which test do you mean?

**Comment by ssrlive** [comment]
OK, Iet's merge it first.

**Pull request merged**
